#!/usr/bin/env python

import os
import shutil
import torch
from diffusers import StableDiffusionLatentUpscalePipeline, StableDiffusionPipeline


MODEL_IDs = [
    "stabilityai/stable-diffusion-2-1",
    "andite/anything-v4.0",
    "runwayml/stable-diffusion-v1-5"
]
MODEL_CACHE = "diffusers-cache"

if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)

for MODEL_ID in MODEL_IDs:
    pipe = StableDiffusionPipeline.from_pretrained(
        MODEL_ID, cache_dir=MODEL_CACHE, torch_dtype=torch.float16
    )

upscaler = StableDiffusionLatentUpscalePipeline.from_pretrained(
    "stabilityai/sd-x2-latent-upscaler",
    cache_dir=MODEL_CACHE,
    torch_dtype=torch.float16,
)
